-- 更新所有 ENUM 类型字段从小写改为大写
-- 注意：MySQL 的 ENUM 类型是区分大小写的，需要修改列定义

-- 1. 更新 users 表的枚举字段
ALTER TABLE users MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'BANNED', 'DELETED') NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users MODIFY COLUMN gender ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');
ALTER TABLE users MODIFY COLUMN education_level ENUM('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'PHD', 'OTHER');

-- 2. 更新 admin_users 表的枚举字段
ALTER TABLE admin_users MODIFY COLUMN role ENUM('SUPER_ADMIN', 'ADMIN', 'EDITOR', 'VIEWER') DEFAULT 'EDITOR';
ALTER TABLE admin_users MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'DISABLED') DEFAULT 'ACTIVE';

-- 3. 更新 comments 表的枚举字段
ALTER TABLE comments MODIFY COLUMN status ENUM('VISIBLE', 'HIDDEN', 'DELETED') NOT NULL DEFAULT 'VISIBLE';

-- 4. 更新 system_configs 表的枚举字段
ALTER TABLE system_configs MODIFY COLUMN value_type ENUM('STRING', 'NUMBER', 'BOOLEAN', 'JSON') NOT NULL DEFAULT 'STRING';

-- 5. 更新 posts 表的枚举字段
ALTER TABLE posts MODIFY COLUMN content_type ENUM('POST', 'QUESTION', 'TIMELINE', 'VLOG') NOT NULL DEFAULT 'POST';
ALTER TABLE posts MODIFY COLUMN status ENUM('DRAFT', 'PUBLISHED', 'DELETED') NOT NULL DEFAULT 'PUBLISHED';

-- 6. 更新 material_checklists 表的枚举字段
ALTER TABLE material_checklists MODIFY COLUMN category ENUM('REQUIRED', 'SUPPORTING', 'OPTIONAL') NOT NULL DEFAULT 'REQUIRED';
ALTER TABLE material_checklists MODIFY COLUMN status ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'SKIPPED') NOT NULL DEFAULT 'NOT_STARTED';

-- 7. 更新 plan_milestones 表的枚举字段
ALTER TABLE plan_milestones MODIFY COLUMN status ENUM('PENDING', 'COMPLETED', 'MISSED') DEFAULT 'PENDING';

-- 8. 更新 notifications 表的枚举字段
ALTER TABLE notifications MODIFY COLUMN type ENUM('SYSTEM', 'LIKE', 'COMMENT', 'FOLLOW', 'REPLY', 'MENTION', 'POLICY_UPDATE') NOT NULL DEFAULT 'SYSTEM';

-- 9. 更新 oauth_connections 表的枚举字段
ALTER TABLE oauth_connections MODIFY COLUMN provider ENUM('WECHAT', 'QQ', 'APPLE', 'GOOGLE', 'GITHUB') NOT NULL;

-- 10. 更新 plans 表的枚举字段
ALTER TABLE plans MODIFY COLUMN plan_type ENUM('STUDY', 'WORK', 'IMMIGRATION') NOT NULL DEFAULT 'STUDY';
ALTER TABLE plans MODIFY COLUMN status ENUM('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE';

-- 11. 更新 country_policies 表的枚举字段
ALTER TABLE country_policies MODIFY COLUMN policy_type ENUM('VISA', 'IMMIGRATION', 'WORK', 'STUDY') NOT NULL DEFAULT 'VISA';
ALTER TABLE country_policies MODIFY COLUMN status ENUM('ACTIVE', 'INACTIVE', 'EXPIRED') DEFAULT 'ACTIVE';

-- 12. 更新 plan_stages 表的枚举字段
ALTER TABLE plan_stages MODIFY COLUMN status ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'NOT_STARTED';

-- 13. 更新 plan_tasks 表的枚举字段
ALTER TABLE plan_tasks MODIFY COLUMN status ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'SKIPPED') NOT NULL DEFAULT 'NOT_STARTED';

